import mongoose from 'mongoose';
import { ScheduleModel, ISchedule } from './model/schedule';
import config from './utility/config';

const rawData = [
  {
    Date: '1120407',
    Code: '1217',
    Name: '愛之味',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '0.400000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120710',
    Code: '1234',
    Name: '黑松',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '1.800000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120414',
    Code: '1315',
    Name: '達新',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '3.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '1477',
    Name: '聚陽',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '14.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120413',
    Code: '1524',
    Name: '耿鼎',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '1.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120602',
    Code: '1587',
    Name: '吉茂',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '1.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120427',
    Code: '1604',
    Name: '聲寶',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '1.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '2006',
    Name: '東和鋼鐵',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '3.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '2015',
    Name: '豐興',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '4.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '2108',
    Name: '南帝',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '2.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120414',
    Code: '2109',
    Name: '華豐',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '0.400000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120413',
    Code: '2313',
    Name: '華通',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '2.700000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120420',
    Code: '2324',
    Name: '仁寶',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '1.200000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '2331',
    Name: '精英',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '0.800000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120710',
    Code: '2359',
    Name: '所羅門',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '1.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120413',
    Code: '2368',
    Name: '金像電',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '3.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120414',
    Code: '2382',
    Name: '廣達',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '6.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120620',
    Code: '2450',
    Name: '神腦',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '2.200000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '2458',
    Name: '義隆',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '3.069257',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120427',
    Code: '2477',
    Name: '美隆電',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '0.800000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '2483',
    Name: '百容',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '1.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120414',
    Code: '2496',
    Name: '卓越',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '3.300000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120413',
    Code: '2528',
    Name: '皇普',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '0.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '2530',
    Name: '華建',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '0.410761',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120420',
    Code: '2535',
    Name: '達欣工',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '2.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120529',
    Code: '2636',
    Name: '台驊投控',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '5.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120407',
    Code: '2884',
    Name: '玉山金',
    Exdividend: '權',
    StockDividendRatio: '',
    SubscriptionRatio: '0.06',
    SubscriptionPricePerShare: '20.00',
    CashDividend: '0',
    SharesOffered: '80000000.00',
    SharesEmpOwner: '120000000.00',
    SharesholderOwner: '600000000.00',
    StockHoldingRatio: '42.03',
  },
  {
    Date: '1120407',
    Code: '3003',
    Name: '健和興',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '2.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120626',
    Code: '3557',
    Name: '嘉威',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '5.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120413',
    Code: '4532',
    Name: '瑞智',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '0.900000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '4930',
    Name: '燦星網',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '2.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '5222',
    Name: '全訊',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '3.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120413',
    Code: '5388',
    Name: '中磊',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '4.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120615',
    Code: '5522',
    Name: '遠雄',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '3.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120706',
    Code: '6128',
    Name: '上福',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '2.200000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120420',
    Code: '6224',
    Name: '聚鼎',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '1.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '6281',
    Name: '全國電',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '5.000000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120330',
    Code: '6581',
    Name: '鋼聯',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '6.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120414',
    Code: '6756',
    Name: '威鋒電子',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '7.488695',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
  {
    Date: '1120419',
    Code: '8926',
    Name: '台汽電',
    Exdividend: '權',
    StockDividendRatio: '',
    SubscriptionRatio: '0.17',
    SubscriptionPricePerShare: '尚未公告',
    CashDividend: '0',
    SharesOffered: '10000000.00',
    SharesEmpOwner: '10000000.00',
    SharesholderOwner: '80000000.00',
    StockHoldingRatio: '135.81',
  },
  {
    Date: '1120413',
    Code: '8996',
    Name: '高力',
    Exdividend: '息',
    StockDividendRatio: '',
    SubscriptionRatio: '',
    SubscriptionPricePerShare: '',
    CashDividend: '1.500000',
    SharesOffered: '',
    SharesEmpOwner: '',
    SharesholderOwner: '',
    StockHoldingRatio: '',
  },
];

const schedules: ISchedule[] = rawData.map((source: any) => {
  const newSchedule: ISchedule = {
    stockNo: source.Code,
    stockName: source.Name,
    year: '2023',
    month: source.Date.substring(3, 5),
    date: (parseInt(source.Date) + 19110000).toFixed(0), //dividend date '20210601'
    cashDividen: parseFloat(source.CashDividend),
    others: [{ key: 'type', value: source.Exdividend }],
    updateDate: '20230406',
    sourceType: '除權息預告',
  };
  return newSchedule;
});

// Connect to MongoDB
mongoose.connect(config.MONGODB_URI).then(async () => {
  await ScheduleModel.deleteMany({ sourceType: '除權息預告' });

  ScheduleModel.insertMany(schedules)
    .then(() => {
      console.log('Batch insert successful');
    })
    .catch((error: any) => {
      console.error('Batch insert failed', error);
    })
    .finally(() => {
      mongoose.disconnect();
    });
});
